import type { FileToCreate } from '../../types';
import type { ClaudeMdSection } from '../claude-md';

export function getWorkflowFiles(
  name: string,
  description?: string
): FileToCreate[] {
  return [
    {
      path: 'docs/spec.md',
      content: `# Feature Specification

> Define the feature's scope, requirements, and acceptance criteria.

## Summary

(Describe the feature.)

## Requirements

- [ ] (List requirements)

## Acceptance Criteria

- [ ] (List criteria)
`,
    },
    {
      path: 'docs/implementation-plan.md',
      content: `# Implementation Plan

> Generated by \`/implementation-plan\` after scope is defined.

(Run \`/implementation-plan\` to populate this file.)
`,
    },
    {
      path: '.claude/commands/scope.md',
      content: `# Scope

Define feature boundaries and acceptance criteria:

1. Read \`docs/spec.md\` (or ask the user to describe the feature)
2. Clarify scope boundaries — what's in, what's out
3. Define acceptance criteria
4. Identify affected areas of the codebase
5. Update \`docs/spec.md\` with finalised scope
`,
    },
    {
      path: '.claude/commands/implementation-plan.md',
      content: `# Implementation Plan

Plan the implementation approach:

1. Read \`docs/spec.md\` for scope and requirements
2. Explore affected codebase areas
3. Design implementation phases with TDD structure
4. Identify risks and dependencies
5. Save plan to \`docs/implementation-plan.md\`
`,
    },
    {
      path: '.claude/commands/pre-review.md',
      content: `# Pre-Review

Self-review before code review:

1. Review all changes against \`docs/spec.md\` acceptance criteria
2. Check for missed edge cases
3. Verify test coverage
4. Check for code style consistency
5. Write a summary of changes for the reviewer
`,
    },
  ];
}

export function getWorkflowClaudeMdSections(): ClaudeMdSection[] {
  return [
    {
      heading: '## Workflow',
      content: `**Preset:** Feature — adding functionality to an existing codebase.

### Phases
1. **Intake** — Understand the feature request, read \`docs/spec.md\`
2. **Explore** — Investigate affected areas of the codebase
3. **Plan** — \`/implementation-plan\` designs the approach with TDD structure
4. **Build** — TDD implementation with automated test loop
5. **Review** — \`/pre-review\` self-check before code review
6. **Handover** — \`/session-handover\` at context boundaries

### PR Preparation
- Run \`/pre-review\` before requesting code review
- Ensure all acceptance criteria from \`docs/spec.md\` are met
- Write clear commit messages describing the "why"`,
      order: 30,
      source: 'workflow',
    },
  ];
}
