import type { FileToCreate } from '../../types';
import type { ClaudeMdSection } from '../claude-md';

export function getWorkflowFiles(
  name: string,
  description?: string
): FileToCreate[] {
  return [
    {
      path: 'docs/brief.md',
      content: `# Project Brief

> Define what you're building and why.

## Vision

(Describe the project's purpose.)

## Key Features

- [ ] (List core features)

## Constraints

- (List technical or business constraints)
`,
    },
    {
      path: 'docs/architecture.md',
      content: `# Architecture

> Generated by \`/architect\` after the brief is defined.

(Run \`/architect\` to populate this file.)
`,
    },
    {
      path: 'docs/build-plan.md',
      content: `# Build Plan

> Generated by \`/build-plan\` after architecture is defined.

(Run \`/build-plan\` to populate this file.)
`,
    },
    {
      path: '.claude/commands/architect.md',
      content: `# Architect

Design the system architecture:

1. Read \`docs/brief.md\` for project vision and constraints
2. Research architectural options (frameworks, patterns, infrastructure)
3. Design system architecture with component diagram
4. Define data model and API boundaries
5. Identify technical risks
6. Save to \`docs/architecture.md\`
`,
    },
    {
      path: '.claude/commands/build-plan.md',
      content: `# Build Plan

Plan the build sequence:

1. Read \`docs/architecture.md\` for system design
2. Break down into buildable phases
3. Define TDD structure per phase
4. Identify deployment requirements
5. Set handover checkpoints with context budget estimates
6. Save to \`docs/build-plan.md\`
`,
    },
    {
      path: '.claude/commands/deploy-check.md',
      content: `# Deploy Check

Pre-deployment verification:

1. Verify all tests pass
2. Check environment configuration
3. Verify build succeeds
4. Review deployment dependencies
5. Check for security issues (exposed secrets, open ports)
6. Confirm deployment target is ready
`,
    },
  ];
}

export function getWorkflowClaudeMdSections(): ClaudeMdSection[] {
  return [
    {
      heading: '## Workflow',
      content: `**Preset:** Greenfield — building something from scratch.

### Phases
1. **Define** — Write project brief in \`docs/brief.md\`
2. **Architect** — \`/architect\` designs system architecture
3. **Plan** — \`/build-plan\` creates phased build sequence
4. **Build** — TDD implementation with automated test loop
5. **Deploy** — \`/deploy-check\` verifies deployment readiness
6. **Handover** — \`/session-handover\` at context boundaries

### Architecture-First Approach
- Always define architecture before writing code
- Use \`docs/architecture.md\` as the source of truth for system design
- Build in phases — each phase should be independently testable`,
      order: 30,
      source: 'workflow',
    },
  ];
}
