import type { FileToCreate } from '../../types';
import type { ClaudeMdSection } from '../claude-md';

export function getWorkflowFiles(
  name: string,
  description?: string
): FileToCreate[] {
  return [
    { path: 'docs/research-notes/.gitkeep', content: '' },
    { path: 'docs/research-output/.gitkeep', content: '' },
    {
      path: 'docs/stack-recommendation.md',
      content: `# Stack Recommendation

> Generated by \`/research-setup\` after analysing research notes.

(Run \`/research-setup\` to populate this file.)
`,
    },
    {
      path: 'docs/implementation-plan.md',
      content: `# Implementation Plan

> Generated by \`/tdd-plan\` after research is complete.

(Run \`/tdd-plan\` to populate this file.)
`,
    },
    {
      path: '.claude/commands/research-setup.md',
      content: `# Research Setup

Analyse the research notes and recommend a full tech stack + CC tooling:

1. Read \`docs/research-notes/\`
2. Identify requirements: compute needs, data types, external services, deployment targets
3. Research candidate languages and frameworks (focus on execution speed)
4. Recommend core stack (language, framework, database — default SQLite unless requirements demand otherwise)
5. Search plugin marketplaces for relevant CC tooling
6. Assess need for custom agents/tools
7. Vet all recommendations (tools check, maintenance check, trusted source)
8. Output to \`docs/stack-recommendation.md\`
9. Wait for human approval before installing
`,
    },
    {
      path: '.claude/commands/tdd-plan.md',
      content: `# TDD Plan

Generate an atomic phased TDD implementation plan from research output:

1. Read \`docs/research-output/\` and \`docs/stack-recommendation.md\`
2. Design implementation phases, each with:
   - Test specifications (what to test, expected behaviour)
   - Test code structure
   - Human-execution markers for all tests
   - Handover checkpoints with context budget estimates
3. Assess whether custom agents/tools are needed
4. Save plan to \`.claude/plans/\` and \`docs/implementation-plan.md\`
`,
    },
  ];
}

export function getWorkflowClaudeMdSections(): ClaudeMdSection[] {
  return [
    {
      heading: '## Workflow',
      content: `**Preset:** Research — from idea capture to validated implementation.

### Phases
1. **Capture** — Human captures research notes (Obsidian, markdown)
2. **Setup** — \`/research-setup\` analyses notes, recommends tech stack + CC tooling
3. **Research** — Deep research via Claude.ai Research feature, output to \`docs/research-output/\`
4. **Plan** — \`/tdd-plan\` generates atomic phased TDD implementation plan
5. **Build** — TDD implementation with automated test loop
6. **Handover** — \`/session-handover\` at context boundaries
7. **Complete** — Final test pass, documentation, audit

### TDD Rules
- Tests are executed by the human or by automation hooks
- CC writes test files and provides execution instructions
- Test results go to \`tests/reports/latest.json\`
- CC reads JSON summary only; dives into logs only on failure investigation
- Commit atomically at each green state`,
      order: 30,
      source: 'workflow',
    },
  ];
}
